<?php

namespace frontend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "documents".
 *
 * @property integer $id
 * @property string $url
 * @property string $category
 * @property string $type
 * @property string $date
 * @property integer $user_id
 */
class Documents extends \yii\db\ActiveRecord
{
    /**
     * @var UploadedFile[]
     */
    public $file_my;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'documents';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['file_my'], 'file'],
            [[ 'user_id'], 'integer'],
            [['date'], 'safe'],
            [['url','category'], 'string', 'max' => 255],
            [['type'], 'string', 'max' => 10],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'url' => 'File',
            'category' => 'Category',
            'type' => 'Type',
            'date' => 'Date',
            'user_id' => 'User ID',
        ];
    }

    /*
     *
     */
    public function afterSave($insert, $changedAttributes)
    {
        $this->user_id = Yii::$app->user->getId();
//        $this->date = date('Y-m-d h:m:s');
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
