<?php

namespace frontend\models;

use frontend\components\Helper;
use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "documents".
 *
 * @property integer $id
 * @property string $url
 * @property string $category
 * @property string $type
 * @property string $date
 * @property integer $user_id
 * @property integer $title
 */
class Documents extends \yii\db\ActiveRecord
{
    /**
     * @var UploadedFile[]
     */
    public $file_my;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'documents';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['file_my'], 'file'],
            [['user_id'], 'integer'],
            [['date'], 'safe'],
            [['url', 'category'], 'string', 'max' => 255],
            [['type','title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'url' => 'File',
            'category' => 'Category',
            'type' => 'Type',
            'date' => 'Date',
            'user_id' => 'Uploaded by',
            'title' => 'Title',
        ];
    }

    public function afterFind()
    {
        $this->date = Helper::GetDate($this->date);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {       $this->user_id = Yii::$app->user->getId();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
